name: Big Logs

on:
  workflow_dispatch:

jobs:
  Filling_the_logs:
    runs-on: ubuntu-latest
    steps:
    - name: echo in a loop First Step
      run: |
        for i in {1..20000}
        do
        (date  && printf "\n" && echo '${{ toJSON(github) }}')
        done


